
version: "3.9"
services:

  app:
    build: ./build
    container_name: contenedor_php
    image: usuario/bookmedik:v1
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - red

  db:
    container_name: servidor_mysql
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - red

volumes:
  mariadb_data:

networks:
  red:

